export const LANGUAGE_LIST_REQUEST = 'LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS = 'LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL = 'LANGUAGE_LIST_FAIL'

export const SET_ACTIVE_LANGUAGE = 'SET_ACTIVE_LANGUAGE';
export const CLEAR_ACTIVE_LANGUAGE = 'CLEAR_ACTIVE_LANGUAGE';