export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const ACTIVE_USER_REQUEST = 'ACTIVE_USER_REQUEST'
export const ACTIVE_USER_SUCCESS = 'ACTIVE_USER_SUCCESS'
export const ACTIVE_USER_FAIL = 'ACTIVE_USER_FAIL'