export const LANGUAGE_LIST_REQUEST = 'LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS = 'LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL = 'LANGUAGE_LIST_FAIL'

export const SET_ACTIVE_LANGUAGE = 'SET_ACTIVE_LANGUAGE';
export const CLEAR_ACTIVE_LANGUAGE = 'CLEAR_ACTIVE_LANGUAGE';

export const ADD_LANGUAGE_REQUEST = 'ADD_LANGUAGE_REQUEST'
export const ADD_LANGUAGE_SUCCESS = 'ADD_LANGUAGE_SUCCESS'
export const ADD_LANGUAGE_FAIL = 'ADD_LANGUAGE_FAIL'

export const UPDATE_LANGUAGE_REQUEST = 'UPDATE_LANGUAGE_REQUEST'
export const UPDATE_LANGUAGE_SUCCESS = 'UPDATE_LANGUAGE_SUCCESS'
export const UPDATE_LANGUAGE_FAIL = 'UPDATE_LANGUAGE_FAIL'

export const DELETE_LANGUAGE_REQUEST = 'DELETE_LANGUAGE_REQUEST'
export const DELETE_LANGUAGE_SUCCESS = 'DELETE_LANGUAGE_SUCCESS'
export const DELETE_LANGUAGE_FAIL = 'DELETE_LANGUAGE_FAIL'

export const GET_COUNTRY_LIST_REQUEST = 'GET_COUNTRY_LIST_REQUEST'
export const GET_COUNTRY_LIST_SUCCESS = 'GET_COUNTRY_LIST_SUCCESS'
export const GET_COUNTRY_LIST_FAIL = 'GET_COUNTRY_LIST_FAIL'

export const UPDATE_LANGUAGE_DISPLAY = 'UPDATE_LANGUAGE_DISPLAY'