# Generated by Django 4.0.2 on 2023-07-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0005_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_users', to='base.language'),
        ),
    ]
