# Generated by Django 4.0.2 on 2023-07-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userword',
            old_name='word',
            new_name='user_word',
        ),
    ]
