# Generated by Django 4.0.2 on 2023-09-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_country_flag_alter_language_image'),
        ('users', '0008_rename_word_userword_user_word'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, to='base.Language'),
        ),
    ]
