# Generated by Django 4.0.2 on 2024-01-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userword_ismastered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='count',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
