# Generated by Django 4.0.2 on 2024-01-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userword_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_rules',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
