# Generated by Django 4.0.2 on 2024-01-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_character_descirption'),
        ('users', '0013_user_confirm_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('count', models.IntegerField(blank=True, default=10, null=True)),
                ('isMastered', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
            options={
                'unique_together': {('user', 'user_character')},
            },
        ),
    ]
