# Generated by Django 4.0.2 on 2023-09-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_country_language_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
