# Generated by Django 4.1.7 on 2023-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_word_language_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
