# Generated by Django 4.1.7 on 2023-04-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_word_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='isCorrect',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
