# Generated by Django 4.1.7 on 2023-04-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_word_iscorrect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spanish',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.word')),
            ],
            bases=('base.word',),
        ),
    ]
