# Generated by Django 4.0.2 on 2023-09-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_country_options_alter_language_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id'], 'verbose_name_plural': 'Countries'},
        ),
    ]
