# Generated by Django 4.1.7 on 2023-04-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_spanish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spanish',
            options={'verbose_name_plural': 'Spanish'},
        ),
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
