# Generated by Django 4.0.2 on 2023-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='countries',
            field=models.ManyToManyField(blank=True, to='base.Country'),
        ),
    ]
