# Generated by Django 4.0.2 on 2024-01-11 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alphabet_word_pronunciation_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='alphabet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='base.alphabet'),
        ),
    ]
