# Generated by Django 4.0.2 on 2024-01-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_character_descirption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='descirption',
            new_name='description',
        ),
    ]
