# Generated by Django 4.0.2 on 2024-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_descirption_character_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pronunciation',
            field=models.JSONField(default=dict),
        ),
    ]
