# Generated by Django 4.0.2 on 2024-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_character_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
