# Generated by Django 4.0.2 on 2024-01-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_word_translationii_word_translationiii'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronunciationII',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciationIII',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
