# Generated by Django 4.0.2 on 2024-01-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_word_pronunciationii_word_pronunciationiii'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
